eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

spring:
  datasource:
    url: jdbc:h2:mem:~
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data: ## default it uses host: localhost and port: 6379
    redis:
      host: localhost
      port: 6379
  cache: ## this for time to live of data which is stored to redis
    redis:
      time-to-live: 10m
#
#    mongodb:
#      uri: 'mongodb://pdp:123@localhost:27017'
#      database: sockets
#      authentication-database: admin
#server:
#  port: 9999