spring:
  data:
    mongodb:
      uri: mongodb://docdb-2024-07-30-10-01-23.cn4icemu2wy9.ap-southeast-1.docdb.amazonaws.com/job
      username: root
      password: Root1234!!
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://104.197.130.41:8762/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

springdoc:
  api-docs:
    path: /api/v1/j/api-docs
  swagger-ui:
    path: /api/v1/j/swagger-ui.html

logging:
  level:
    root: warn
  file:
    name: figure-this-shit-out.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"