spring:
  datasource:
    url: jdbc:postgresql://database-2.cn6kg88w28oy.eu-north-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: Root1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/master.yaml
    enabled: false
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://ec2-51-20-67-130.eu-north-1.compute.amazonaws.com:8762/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

springdoc:
  api-docs:
    path: /api/v1/j/api-docs
  swagger-ui:
    path: /api/v1/j/swagger-ui.html

  data: ## default it uses host: localhost and port: 6379
    redis:
      host: localhost
      port: 6379
  cache: ## this for time to live of data which is stored to redis
    redis:
      time-to-live: 10m

logging:
  level:
    root: warn
  file:
    name: figure-this-shit-out.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"