package com.jobhunter.appjobfestservice.utils;

import java.util.function.Supplier;

public interface MessageConstants {
    String ABOUT_CAN_NOT_BE_BLANK = "ABOUT RESUME CANNOT BE BLANK";
    String SKILLS_CAN_NOT_BE_NULL = "SKILLS CANNOT BE NULL";
    String EXPERIENCES_CAN_NOT_BE_NULL = "EXPERIENCES CANNOT BE NULL";
    String EDUCATION_LIST_CANNOT_BE_NULL = "EDUCATION LIST CANNOT BE NULL";
    String LANGUAGES_LIST_CANNOT_BE_NULL = "LANGUAGES LIST CANNOT BE NULL";
    String INVALID_RESUME_ID = "INVALID RESUME ID";
    String SUCCESS = "SUCCESS";
    String RESUME_ALREADY_EXISTS = "RESUME ALREADY EXISTS";
    String COMPANY_NAME_CANNOT_BE_NULL = "COMPANY NAME CANNOT BE NULL";
    String START_DATE_CANNOT_BE_NULL = "START DATE CANNOT BE NULL";
    String POSITION_CANNOT_BE_NULL = "POSITION CANNOT BE NULL";
    String DESCRIPTION_OF_EXPERIENCE_CANNOT_BE_NULL = "DESCRIPTION OF EXPERIENCE CANNOT BE NULL";
    String TYPE_OF_EDUCATION_CANNOT_BE_NULL = "TYPE OF EDUCATION CANNOT BE NULL";
    String NAME_OF_EDUCATION_CANNOT_BE_NULL = "NAME OF EDUCATION CANNOT BE NULL";
    String LANGUAGE_CANNOT_BE_NULL = "LANGUAGE CANNOT BE NULL";
    String LANGUAGE_LEVEL_CANNOT_BE_NULL = "LANGUAGE LEVEL CANNOT BE NULL";
    String INVALID_SPECIALIZATION_ID = "INVALID SPECIALIZATION ID";
    String PLEASE_CREATE_A_RESUME = "PLEASE, CREATE A RESUME";
    String INVALID_EXPERIENCE_ID = "INVALID EXPERIENCE ID";
    String INVALID_EDUCATION_ID = "INVALID EDUCATION ID";
    String INVALID_LANGUAGE_ID = "INVALID LANGUAGE ID";
}
